#!/usr/bin/env python
"""
OAuth Connection Diagnostics
Helps debug "localhost refused to connect" errors during Google OAuth flow.
Run: python oauth_diagnostics.py
"""

import os
import sys
import socket
import json
from pathlib import Path
from urllib.parse import urljoin

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')

import django
django.setup()

from django.test import RequestFactory
from django.urls import reverse
import requests

def print_header(text):
    print(f"\n{'='*70}")
    print(f"  {text}")
    print(f"{'='*70}\n")

def print_subheader(text):
    print(f"\n▶ {text}")
    print(f"{'-'*70}")

def check_server_running():
    """Check if Django dev server is running on expected ports"""
    print_subheader("1. Django Development Server Status")
    
    ports_to_check = [8000, 5000, 3000, 8080]
    running_on = None
    
    for port in ports_to_check:
        try:
            sock = socket.create_connection(("127.0.0.1", port), timeout=1)
            sock.close()
            print(f"  ✅ Server appears to be running on port {port}")
            running_on = port
            break
        except (socket.timeout, ConnectionRefusedError):
            print(f"  ⚠️  Port {port}: No response")
    
    if not running_on:
        print(f"\n  ❌ Django server not found on common ports (8000, 5000, 3000, 8080)")
        print(f"\n  💡 FIX: Start the dev server with:")
        print(f"     python manage.py runserver 0.0.0.0:8000")
        return False, None
    
    return True, running_on

def check_callback_url_accessibility(port):
    """Test if callback URL is accessible"""
    print_subheader("2. Callback URL Accessibility")
    
    callback_urls = [
        f"http://localhost:{port}/auth/callback/",
        f"http://127.0.0.1:{port}/auth/callback/",
    ]
    
    for url in callback_urls:
        try:
            response = requests.get(url, timeout=2, allow_redirects=False)
            print(f"  ✅ {url}")
            print(f"     Status: {response.status_code}")
            return True, url
        except requests.exceptions.ConnectionError:
            print(f"  ❌ {url} - Connection refused")
        except Exception as e:
            print(f"  ⚠️  {url} - {type(e).__name__}")
    
    return False, None

def check_supabase_config():
    """Check Supabase configuration"""
    print_subheader("3. Supabase OAuth Configuration")
    
    url = os.getenv('SUPABASE_URL')
    key = os.getenv('SUPABASE_KEY')
    
    if not url or not key:
        print(f"  ❌ SUPABASE_URL or SUPABASE_KEY not set in .env")
        return False
    
    print(f"  ✅ Supabase credentials found")
    print(f"     URL: {url[:50]}...")
    
    # Note: We can't directly query Supabase OAuth settings from here
    # but we can provide guidance
    print(f"\n  ⚠️  CRITICAL: Verify Supabase OAuth configuration manually:")
    print(f"     1. Go to: https://app.supabase.com/")
    print(f"     2. Select your project")
    print(f"     3. Go to: Authentication → Providers → Google")
    print(f"     4. Check these redirect URIs are configured:")
    print(f"        - http://localhost:8000/auth/callback/")
    print(f"        - http://localhost/auth/callback/")
    print(f"        - https://nexassearch.com/auth/callback/ (production)")
    print(f"\n     If NOT configured, that's why you're getting 'localhost refused'!")
    
    return True

def generate_expected_callback_urls():
    """Show what callback URLs the code would generate"""
    print_subheader("4. Expected Callback URLs (Generated by Django)")
    
    factory = RequestFactory()
    
    # Test different request scenarios
    test_hosts = [
        ('localhost:8000', None, 'Basic localhost'),
        ('alice.localhost:8000', 'alice', 'Localhost with subdomain'),
        ('localhost', None, 'Localhost port 80'),
        ('beddingsavenue.nexassearch.com', 'beddingsavenue', 'Production domain'),
    ]
    
    print(f"\n  Expected callback URLs based on request hostname:")
    
    for host, subdomain, description in test_hosts:
        request = factory.get('/', HTTP_HOST=host)
        request.subdomain = subdomain
        
        # Simulate the oauth callback URL generation
        if 'localhost' in host and '.' in host:
            # localhost with subdomain - strip subdomain
            parts = host.split('.')
            base_host = '.'.join(parts[-2:])
            callback_url = f"{request.scheme}://{base_host}/auth/callback/"
        else:
            callback_url = f"{request.scheme}://{request.get_host()}/auth/callback/"
        
        print(f"  • {description:40} → {callback_url}")

def check_django_urls():
    """Verify Django URLs are configured"""
    print_subheader("5. Django URL Routes")
    
    try:
        url = reverse('auth_callback')
        print(f"  ✅ auth_callback route found: {url}")
        
        url = reverse('google_login')
        print(f"  ✅ google_login route found: {url}")
        
        return True
    except Exception as e:
        print(f"  ❌ URL route error: {e}")
        return False

def check_environment_vars():
    """Check OAuth environment variables"""
    print_subheader("6. Environment Variables")
    
    oauth_callback_base = os.getenv('OAUTH_CALLBACK_BASE')
    debug = os.getenv('DEBUG')
    allowed_hosts = os.getenv('ALLOWED_HOSTS')
    
    if oauth_callback_base:
        print(f"  ✅ OAUTH_CALLBACK_BASE set: {oauth_callback_base}")
    else:
        print(f"  ⚠️  OAUTH_CALLBACK_BASE not set (will auto-detect from request)")
    
    print(f"  • DEBUG: {debug}")
    print(f"  • ALLOWED_HOSTS: {allowed_hosts}")

def show_solution():
    """Show step-by-step solution"""
    print_subheader("7. Step-by-Step Solution")
    
    print("""
  PROBLEM: "localhost refused to connect" during Google OAuth
  
  ROOT CAUSE: Your callback URL is not registered in Supabase's OAuth settings
  
  SOLUTION - Register Callback URL in Supabase:
  
  Step 1: Go to Supabase Dashboard
          https://app.supabase.com → Select your project
  
  Step 2: Navigate to Authentication
          Left sidebar → Authentication → Providers → Google
  
  Step 3: Copy these exact callback URLs into the "Redirect URLs" field
          (one per line, if supported, or add multiple times)
          
          For Local Development:
          ✅ http://localhost:8000/auth/callback/
          ✅ http://127.0.0.1:8000/auth/callback/
          
          For Production:
          ✅ https://nexassearch.com/auth/callback/
          ✅ https://beddingsavenue.nexassearch.com/auth/callback/
          ✅ https://*.nexassearch.com/auth/callback/
  
  Step 4: Click SAVE
  
  Step 5: Restart your Django server (if it was running before step 1)
          Ctrl+C to stop, then: python manage.py runserver 0.0.0.0:8000
  
  Step 6: Test again
          Click "Google" button on login page
          Should see Google login screen (not "localhost refused")
""")

def run_diagnostics():
    """Run all diagnostic checks"""
    print_header("OAUTH CONNECTION DIAGNOSTICS - Google Login Troubleshoot")
    
    server_running, port = check_server_running()
    
    if not server_running:
        print(f"\n⚠️  REQUIRED: Start the Django dev server before testing OAuth")
        return False
    
    accessible, callback_url = check_callback_url_accessibility(port)
    check_supabase_config()
    generate_expected_callback_urls()
    check_django_urls()
    check_environment_vars()
    show_solution()
    
    print_header("SUMMARY")
    
    if server_running and accessible:
        print("""
  ✅ Your server is running and callback URL is accessible
  ❌ If you're still getting "localhost refused", the issue is:
  
     → Callback URL NOT registered in Supabase OAuth settings
     
  ACTION: 
  1. Go to Supabase → Authentication → Providers → Google
  2. Add callback URL to the "Redirect URLs" field
  3. SAVE
  4. Try Google login again
""")
    elif server_running and not accessible:
        print("""
  ⚠️  Django server is running but callback URL not accessible
  
  POSSIBLE CAUSES:
  1. Django registered for different host/port than tested
  2. ALLOWED_HOSTS doesn't include the domain you're using
  3. Different issue with server configuration
""")
    else:
        print("""
  ❌ Django server not running
  
  FIX: Start the server
       python manage.py runserver 0.0.0.0:8000
  
  Then test Google login again
""")

if __name__ == '__main__':
    try:
        run_diagnostics()
    except Exception as e:
        print(f"\n❌ Diagnostic error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
