# Generated by Django 6.0 on 2026-01-05 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('business_address', models.TextField(blank=True, null=True)),
                ('business_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('logo_small_url', models.TextField(blank=True, null=True)),
                ('cover_small_url', models.TextField(blank=True, null=True)),
                ('category_pillar', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='category_icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.category')),
            ],
        ),
    ]
